sonar.projectKey=todo-app
sonar.projectName=Todo App
sonar.sourceEncoding=UTF-8

# Source code location
sonar.sources=.

# Exclude unnecessary files
sonar.exclusions=vendor/**,database/**,.github/**,k8s/**,images/**,**/*.md
