apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::103731055876:role/eksctl-duosecops-cluster-nodegroup-NodeInstanceRole-SOfdaGUBoRWj
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2026-07-24T17:38:54Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1326"
  uid: 13769400-d2da-411a-aa3f-a2295c19bb8a
