apiVersion: v1
kind: Secret
metadata:
  name: todo-db-secret
  namespace: todo-app
type: Opaque
stringData:
  DB_HOST: todo-app.calswc2sawob.us-east-1.rds.amazonaws.com
  DB_USER: todo_user
  DB_PASS: duosecops
  DB_NAME: mytododb
