name: Deploy Todo App to EKS

on:
  push:
    branches:
      - main


jobs:

  deploy:

    runs-on: ubuntu-latest


    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    - name: Cache SonarQube packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: SonarQube Quality Gate Check
      uses: SonarSource/sonarqube-quality-gate-action@v1.2.0
      timeout-minutes: 5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4

      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        aws-region: us-east-1


    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2


    - name: Build Docker Image
      run: |

        docker build -t duosecops .


    - name: Tag Docker Image
      run: |

        docker tag duosecops:latest \
        103731055876.dkr.ecr.us-east-1.amazonaws.com/duosecops:${{ github.sha }}

    - name: Run Trivy Image Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 103731055876.dkr.ecr.us-east-1.amazonaws.com/duosecops:${{ github.sha }}
        format: table
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'HIGH,CRITICAL'

    - name: Push Image to ECR
      run: |

        docker push \
        103731055876.dkr.ecr.us-east-1.amazonaws.com/duosecops:${{ github.sha }}


    - name: Configure kubectl for EKS
      run: |

        aws eks update-kubeconfig \
        --name duosecops-cluster \
        --region us-east-1


    - name: Update Kubernetes Manifest
      run: |

        sed -i "s|IMAGE_PLACEHOLDER|103731055876.dkr.ecr.us-east-1.amazonaws.com/duosecops:${{ github.sha }}|g" k8s/deployment.yaml

    - name: Create Kubernetes Secret
      run: |
        kubectl create secret generic todo-db-secret \
          --from-literal=DB_HOST="${{ secrets.DB_HOST }}" \
          --from-literal=DB_USER="${{ secrets.DB_USER }}" \
          --from-literal=DB_PASS="${{ secrets.DB_PASS }}" \
          --from-literal=DB_NAME="${{ secrets.DB_NAME }}" \
          --namespace todo-app \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy Kubernetes Resources
      run: |

        kubectl apply -f k8s/ -n todo-app

    - name: Verify Deployment Rollout
      run: |

        kubectl rollout status deployment/todo-app \
        -n todo-app \
        --timeout=120s
    - name: Rollback Deployment
      if: failure()
      run: |
        echo "Deployment failed. Rolling back..."

        kubectl rollout undo deployment/todo-app -n todo-app

        kubectl rollout status deployment/todo-app -n todo-app
